---
- hosts: 172.31.40.115
  become: yes
  tasks: 
  - name:  i want to execute direct linux command 
    command: sudo apt-get install apache2 
    register: myresult

  - name: i want  to display my  first task result 
    debug:
        msg: "{{myresult}}"