---
- hosts: 172.31.40.115 
  become: yes
  tasks:
  - name: install git 
    apt:
      name: git
      state: present 

  - name: install wget
    apt: 
      name: wget
      state: present
    ignore_errors: true


  - name: install tree
    apt:
      name: tree
      state: present

  