---
- hosts: 172.31.5.33
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a folder
    file:
       path: /home/maha/myfolder
       state: directory
    
  - name: install apache2 
    apt:
      name: apache2
      state: present
    

