---
- hosts: 172.31.5.33
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a folder
    file:
       path: /home/maha/myfolder
       state: directory

  - name: copy file from master to nodes
    copy:
      src: mystaticfile
      dest: /home/maha/myfolder

  - name:  download remote files (internet)
    get_url:
      url: https://github.com/maha4dsvc/myAnsible_DS_M_6am_16feb26/blob/main/installjava.yml
      dest: /home/maha/myfolder/installjava.yml
      force_basic_auth: yes

  - name:  copy index.j2 file into nodes side
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: startwebserver

  - name: install apache2 
    apt:
      name: apache2
      state: present
      
  handlers: 
  - name: startwebserver
    service: 
       name: apache2
       state: started
      

